Full Desktop Version of My Portfolio
rubydevi/my-portfolio pull request #5
Opened 2023-05-11 13:16 UTC by rubydevi

**Desktop Version For My Portfolio**

- I wrote all the styles for the desktop version inside the media query.
- Styled using mainly grid and flex as instructed
- Minimum width set to 768px
- Hid some buttons in the desktop version
- Added hover function for all buttons and work section's card.

2023-05-11 14:01 UTC, AlphaNtihinduka requested changes
## Hi @rubydevi 🙋‍♂️
Good job working on your portifolio desktop version. You have done the design to the best expectation and incredibly well. 👏  

You still need to implement few on the project but you are almost there!!! :watch: 

TO HIGHLIGHT:
- The about section matches the Figma template design ✔️ 
- You did great to use the desktop background images ✔️
- Your contact section design is also nice and responsive. ✔️
- Well-structured files ✅

# STATUS: Required Changes :recycle: 

![close](https://user-images.githubusercontent.com/99394374/210771148-619a4265-33b2-4e68-8901-6bb52693d6de.gif)

## Optional suggestions
- No optional suggestions
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or slack channel if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK :crossed_fingers: :four_leaf_clover:

2023-05-11 14:01 UTC, AlphaNtihinduka commented on style.css
> +  }
- I suggest to ensure that the width of the container is flexible so that the heading and the paragraph are matching the Figma template design. At this desktop screen size of about `830px`, the texts are overlapping into the image and therefore are hard to read the message content. Kindly try as much as possible to follow the guideline ☺️.

Your design 😎 
![image](https://github.com/rubydevi/my-portfolio/assets/99394374/1bb67362-5261-42d0-9550-b7a131524a44)

Figma template design 😎 
![image](https://github.com/rubydevi/my-portfolio/assets/99394374/6b03e5de-d167-41b8-80dc-353ec8946b93)

2023-05-11 14:01 UTC, AlphaNtihinduka commented on style.css
> +  }
- [  ] Again, at the desktop screen size of around `830px` the body-card contents are squeezed due to the fixed width used. This means that the card contents can not flexibly adapt to different desktop screen sizes. Kindly ensure that this is fixed to match the Figma design and also ensure that the spacing below the image is fixed ☺️. In fact the `card-body` should occupy at most 30% width of the screen size. In addition the spacing on the left and right of the main-container-works section, should be matching the Figma template design 😎. 
- [ ] The button and list of the items should also match the figma design 
Your design 😎 
![image](https://github.com/rubydevi/my-portfolio/assets/99394374/a1352baa-29ce-48aa-86a7-76d99556139c)

Figma design 😎 
![image](https://github.com/rubydevi/my-portfolio/assets/99394374/7d38aa06-ea84-43b1-8fff-75605e6c26a8)


Your design 😎

2023-05-11 14:01 UTC, AlphaNtihinduka commented on style.css
> +  }
- [ ] Please ensure that the card grid section is also fixed so that the cards occupy the section to match the figma template design.

Your design 😎 
![image](https://github.com/rubydevi/my-portfolio/assets/99394374/32af0144-7109-4855-9bc0-3be0d3beba25)

Figm template design 😎 
![image](https://github.com/rubydevi/my-portfolio/assets/99394374/6d81e64e-6948-4ab0-8f80-56a302227d52)

2023-05-12 11:59 UTC, topeogunleye approved these changes
### Hi @rubydevi, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- Ensured Portfolio matched figma design ✔️ 
- Ensure the project card grid section matched the figma design ✔️ 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and description :heavy_check_mark:
 
## [Optional] suggestions:
* nothing to mention.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-12 12:02 UTC, rubydevi commented
It is always very satisfying to see approval. Thanks @topeogunleye and @AlphaNtihinduka

2023-05-12 12:02 UTC, merged